// Generated by CoffeeScript 1.6.3
(function() {
  var allConfigs, defaultConfig, deleteConfig, loadConfig, loadConfigs, loadIndex, localStorage, publicConfig, saveConfig, saveConfigs, saveIndex;

  localStorage = window.localStorage;

  publicConfig = {
    server: '209.141.36.62',
    server_port: 8348,
    local_port: 1080,
    password: '$#HAL9000!',
    method: 'aes-256-cfb',
    timeout: 600
  };

  defaultConfig = {
    server_port: 8388,
    local_port: 1080,
    method: 'aes-256-cfb',
    timeout: 600
  };

  loadConfigs = function() {
    return JSON.parse(localStorage['configs'] || '[]');
  };

  allConfigs = function() {
    var c, configs, e, i, result;
    if (localStorage['configs']) {
      result = [];
      try {
        configs = loadConfigs();
        for (i in configs) {
          c = configs[i];
          result.push("" + c.server + ":" + c.server_port);
        }
        return result;
      } catch (_error) {
        e = _error;
      }
    }
    return [];
  };

  saveIndex = function(index) {
    return localStorage['index'] = index;
  };

  loadIndex = function() {
    return +localStorage['index'];
  };

  saveConfigs = function(configs) {
    return localStorage['configs'] = JSON.stringify(configs);
  };

  saveConfig = function(index, config) {
    var configs;
    if (index === -1) {
      index = NaN;
    }
    configs = loadConfigs();
    if (isNaN(index)) {
      configs.push(config);
      index = configs.length - 1;
    } else {
      configs[index] = config;
    }
    saveConfigs(configs);
    return index;
  };

  loadConfig = function(index) {
    var configs;
    if (isNaN(index)) {
      return defaultConfig;
    }
    if (index === -1) {
      return publicConfig;
    }
    configs = loadConfigs();
    return configs[index] || defaultConfig;
  };

  deleteConfig = function(index) {
    var configs;
    if ((!isNaN(index)) && !(index === -1)) {
      configs = loadConfigs();
      configs.splice(index, 1);
      return saveConfigs(configs);
    }
  };

  exports.allConfigs = allConfigs;

  exports.saveConfig = saveConfig;

  exports.loadConfig = loadConfig;

  exports.deleteConfig = deleteConfig;

  exports.loadIndex = loadIndex;

  exports.saveIndex = saveIndex;

  exports.publicConfig = publicConfig;

}).call(this);
