// Generated by CoffeeScript 1.6.2
(function() {
  var gui, load, local, restartServer, saveChanges, util;

  gui = require('nw.gui');

  util = require('util');

  util.log = function(s) {
    return console.log(new Date().toLocaleString() + (" - " + s));
  };

  local = require('./shadowsocks-nodejs/local');

  saveChanges = function() {
    var config;

    config = {};
    $('input').each(function() {
      var key;

      key = $(this).attr('data-key');
      config[key] = this.value;
      return window.localStorage.setItem(key, this.value);
    });
    console.log('config saved.');
    restartServer(config);
    return false;
  };

  load = function() {
    var config;

    config = {};
    $('input').each(function() {
      var key;

      key = $(this).attr('data-key');
      this.value = window.localStorage.getItem(key) || '';
      return config[key] = this.value;
    });
    return restartServer(config);
  };

  restartServer = function(config) {
    var e, start;

    if (config.server && +config.server_port && config.password && +config.local_port) {
      start = function() {
        if (window.local == null) {
          window.local = local.createServer(config.server, config.server_port, config.local_port, config.password, null, 600);
        }
        return $('#divError').hide();
      };
      if (window.local != null) {
        try {
          return window.local.close(function() {
            window.local = null;
            return start();
          });
        } catch (_error) {
          e = _error;
          return util.log(e);
        }
      } else {
        return start();
      }
    } else {
      return $('#divError').show();
    }
  };

  $('#buttonSave').on('click', saveChanges);

  $('#buttonConsole').on('click', function() {
    return gui.Window.get().showDevTools();
  });

  load();

}).call(this);
